apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsfpvc
  namespace: lsf
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  storageClassName: ""