#--------------------------------------------------------
# Copyright IBM Corp.  2020. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#--------------------------------------------------------
# IBM Spectrum LSF Operator
#

FROM quay.io/operator-framework/ansible-operator:v1.18.0

LABEL name="lsf-operator-@NARCH@" \
      vendor="IBM" \
      version="@VERSION@" \
      release="1" \
      summary="LSF Operator Image" \
      description="This image contains the operator for installing LSF on Kubernetes."

COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible

COPY watches.yaml ${HOME}/watches.yaml
COPY roles/ ${HOME}/roles/
